### PR TITLE
Vendor gardener/gardener@f6b4e24

### PR DESCRIPTION
**Pull request by ialidzhikov**
**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by minchaow — APPROVED** [review]
/lgtm

**Comment by minchaow** [comment]
this commit https://github.com/gardener/gardener/commit/f6b4e243beaecde35d03c9d2adf00536a88ed794 will also be cherry-picked into g/g hotfix?

**Comment by ialidzhikov** [comment]
> this commit [gardener/gardener@f6b4e24](https://github.com/gardener/gardener/commit/f6b4e243beaecde35d03c9d2adf00536a88ed794) will also be cherry-picked into g/g hotfix?

If an extension vendors v1.14.x and it cannot update to gardener/gardener@master for some reasons, then we can cherry-pick it. Do you need the cherry-pick for specific reason?

**Comment by minchaow** [comment]
> > this commit [gardener/gardener@f6b4e24](https://github.com/gardener/gardener/commit/f6b4e243beaecde35d03c9d2adf00536a88ed794) will also be cherry-picked into g/g hotfix?
> 
> If an extension vendors v1.14.x and it cannot update to gardener/gardener@master for some reasons, then we can cherry-pick it. Do you need the cherry-pick for specific reason?

just out of curiosity :)

**Pull request merged**
