### PR TITLE
Replace infra Helm chart with native Go templates

### PR DESCRIPTION
**Pull request by minchaow**
**How to categorize this PR?**

/area open-source
/kind cleanup
/platform alicloud

**What this PR does / why we need it**:
This PR is to replace infra Helm chart with native Go templates.
The same to the PR https://github.com/gardener/gardener-extension-provider-aws/pull/332

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
None
```

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
Very nice, thank you!
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
