### PR TITLE
Adjust component resources request and limits

### PR DESCRIPTION
**Pull request by shaoyongfeng**
**How to categorize this PR?**
/area auto-scaling
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
The resource request and limits for components (seed and shoot) managed by the `provider-alicloud` extension are adjusted based on a production environment analysis with the goal to provide more meaningful resource values.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The resource requests and limits for components (seed and shoot) managed by the `provider-alicloud` extension has been adapted based on a production environment analysis. This is done to avoid OOMKills and cpu throttling situations. Furthermore the vpa `minAllowed` settings are now aligned with the cpu and memory request of the respective component`

```

### CODE REVIEW

**Review by kon-angelo — DISMISSED** [review]
/lgtm

**Review by EmoinLanyu — APPROVED** [review]

**Review by EmoinLanyu — APPROVED** [review]
/lgtm

**Pull request merged**
