### PR TITLE
update deprecated fields

### PR DESCRIPTION
**Pull request by minchaow**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
This PR is to update deprecated fields in TF scripts

Depends on https://github.com/gardener/terraformer/pull/95
**Which issue(s) this PR fixes**:
Fixes #
None
**Special notes for your reviewer**:

**Release note**:

```other operator
None
```

### CODE REVIEW

**Comment by vpnachev** [comment]
This one depends on https://github.com/gardener/gardener-extension-provider-alicloud/pull/306, right?

**Comment by minchaow** [comment]
> This one depends on #306, right?

yes, I've approved the PR #306.

**Comment by ialidzhikov** [comment]
@minchaow , can you check why the integration test fails?

```
last error: the stack 2d20befc-c193-4c9f-822f-f247ee929768 is still in processing state: CREATE_IN_PROGRESS"
```

It seems not directly related to this PR but rather to https://github.com/gardener/gardener-extension-provider-alicloud/pull/281 (/cc @jia-jerry),

**Comment by jia-jerry** [comment]
> @minchaow , can you check why the integration test fails?
> 
> ```
> last error: the stack 2d20befc-c193-4c9f-822f-f247ee929768 is still in processing state: CREATE_IN_PROGRESS"
> ```
> 
> It seems not directly related to this PR but rather to #281 (/cc @jia-jerry),

we add one scenario of VM image encryption, which will take extra time and might cause time out issue. @schrodit , would you help extend the timeout?

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by jia-jerry — APPROVED** [review]

**Comment by schrodit** [comment]
> > @minchaow , can you check why the integration test fails?
> > ```
> > last error: the stack 2d20befc-c193-4c9f-822f-f247ee929768 is still in processing state: CREATE_IN_PROGRESS"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems not directly related to this PR but rather to #281 (/cc @jia-jerry),
> 
> we add one scenario of VM image encryption, which will take extra time and might cause time out issue. @schrodit , would you help extend the timeout?

you can increase the timeout of your test in the testdefinition: https://github.com/gardener/gardener-extension-provider-alicloud/blob/master/.test-defs/infrastructure-test.yaml#L7
(you can also edit this value in the PR to take affect)

**Pull request merged**
