### PR TITLE
bump prometheus/client_golang

### PR DESCRIPTION
**Pull request by FriedrichWilken**
this PR bumps `github.com/prometheus/client_golang` and `sigs.k8s.io/controller-runtime` to `v0.11.1`.

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @FriedrichWilken for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by FriedrichWilken** [comment]
The tests also failed on my machine. I thought this would be a quick and easy fix. But it looks like I have to do some adjustments first. ¯\_(ツ)_/¯

**Pull request closed without merging**
