### PR TITLE
Use provider specific regex to parse error codes from error

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
This PR removes extension dependency on g/g to extract error codes from errors and uses regex defined in the extension repo. Later extensions can be adapted to map provider-specific error codes to gardener error codes.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/5444

**Special notes for your reviewer**:

**Release note**:

```other operator
Provider-specific error codes are now detected/parsed on provider-extension side.
```

### CODE REVIEW

**Comment by shaoyongfeng** [comment]
Hi @acumino ,
can you look into the infra testing failure?

**Comment by acumino** [comment]
> Testrun: [e2e-hb5mm](https://tm.gardener.cloud/testrun/default/e2e-hb5mm) Workflow: e2e-hb5mm-wf Phase: Succeeded
> 
> +---------------------+---------------------+-----------+----------+
> |        NAME         |        STEP         |   PHASE   | DURATION |
> +---------------------+---------------------+-----------+----------+
> | bastion-test        | bastion-test        | Succeeded | 8m46s    |
> | infrastructure-test | infrastructure-test | Succeeded | 12m10s   |
> +---------------------+---------------------+-----------+----------+

@shaoyongfeng failing test is fixed. PTAL

**Review by shaoyongfeng — APPROVED** [review]

**Pull request merged**
