### PR TITLE
Revendor `gardener/gardener@v1.43.2`

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
Revendor `gardener/gardener@v1.43.2`

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by EmoinLanyu — DISMISSED** [review]
/lgtm

**Review by EmoinLanyu — APPROVED** [review]

**Comment by timebertt** [comment]
Can we proceed with this PR? I'm already working on vendoring the next gardener release (v1.44.0) :)

**Pull request merged**
