### PR TITLE
Refactor infrastructure validation with ConfigValidator

### PR DESCRIPTION
**Pull request by kevin-lacoo**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
Refactor infrastructure validation with ConfigValidator, move API depends checks like Enhance NatGateway availableZone check from admission to ConfigValidator.
**Which issue(s) this PR fixes**:
Fixes #
https://github.com/gardener/gardener-extension-provider-alicloud/issues/489

**Special notes for your reviewer**:

**Release note**:

```other operator
Enhance NatGateway availableZone validation is moved to ConfigValidator, If first zone user sets under network section doesn't support enhance natgateway, an error will occur during shoot reconcile process.
```

### CODE REVIEW

**Review by shaoyongfeng — DISMISSED** [review]

**Review by shaoyongfeng — APPROVED** [review]

**Comment by shafeeqes** [comment]
Does this PR fix https://github.com/gardener/gardener-extension-provider-alicloud/issues/489?

**Comment by kevin-lacoo** [comment]
> Does this PR fix #489?

Yes, we removed API depends call from admission-alicloud in this PR.

**Pull request merged**
