### PR TITLE
Upgrade to go 1.19

### PR DESCRIPTION
**Pull request by shafeeqes**
**How to categorize this PR?**

/area quality
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
Upgrade go to 1.19.
Update golang builder images.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Update golang version used to 1.19.1
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
Updated `branch.cfg` 7b9b6200cc33a41643aa885aa0733c2208cff375

**Review by shaoyongfeng — APPROVED** [review]

**Comment by ialidzhikov** [comment]
@shafeeqes "thanks" for leaving the `release-v1.40` branch with broken go version - ref https://github.com/gardener/gardener-extension-provider-alicloud/commit/7b9b6200cc33a41643aa885aa0733c2208cff375!

**Comment by shafeeqes** [comment]
> FYI, I fixed the release-v1.30 pipeline with [8bab9b8](https://github.com/gardener/gardener-extension-provider-alicloud/commit/8bab9b8794a7a85e9018881e106ccf721ccfbf32). With go1.19 it was running always (OOM?) killed and `make check` was always failing.

Thanks, We should then probably use go 1.17.5 for the other release branches as well?

**Pull request merged**
