### PR TITLE
Update to ginkgo@v2

### PR DESCRIPTION
**Pull request by jia-jerry**
**How to categorize this PR?**

/area testing
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Review by shaoyongfeng — DISMISSED** [review]

**Review by shaoyongfeng — APPROVED** [review]

**Review by shaoyongfeng — DISMISSED** [review]

**Review by ialidzhikov — CHANGES_REQUESTED** [review]
The following diff has to be applied to prevent a warning because of a deprecated flag usage:
```diff
diff --git a/.test-defs/infrastructure-test.yaml b/.test-defs/infrastructure-test.yaml
index b43548c5..2c37beab 100644
--- a/.test-defs/infrastructure-test.yaml
+++ b/.test-defs/infrastructure-test.yaml
@@ -10,7 +10,7 @@ spec:
   args:
     - >-
       go test -timeout=0 -mod=vendor ./test/integration/infrastructure
-      --v -ginkgo.v -ginkgo.progress -ginkgo.noColor
+      --v -ginkgo.v -ginkgo.progress -ginkgo.no-color
       --kubeconfig=$TM_KUBECONFIG_PATH/testmachinery.config
       --access-key-id=$ACCESS_KEY_ID
       --access-key-secret=$ACCESS_KEY_SECRET
```

**Comment by ialidzhikov** [comment]
Do we know why the integration test still fails?

**Comment by jia-jerry** [comment]
> Do we know why the integration test still fails?

It took too long for encrypted image copy to finish. Around 2 hours some time.

**Review by ialidzhikov — DISMISSED** [review]
/lgtm

But I would like to see a successful integration test run before proceeding with this PR.

**Review by shaoyongfeng — APPROVED** [review]

**Pull request merged**
