### PR TITLE
[ci:component:github.com/gardener/terraformer:v2.1.0->v2.1.1]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes*:
``` bugfix operator github.com/gardener/terraformer #72 @timebertt
A bug was fixed that caused terraform to leak its finalizer on ConfigMaps and Secrets in case of an interrupt during `terraform destroy`.
```

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
/lgtm

**Comment by timebertt** [comment]
@jia-jerry @minchaow Can you check the integration test failure?

**Comment by minchaow** [comment]
> @jia-jerry @minchaow Can you check the integration test failure?

@timebertt  From a quick look, the error looks caused by the incorrect configuration inside specified VPC. I will have a detailed check later.

> Error reconciling infrastructure: ambiguous VPC response: expected 1 VPC but got []

**Comment by minchaow** [comment]
Hi @timebertt, could we close this PR because of the PR https://github.com/gardener/gardener-extension-provider-alicloud/pull/238?

**Comment by timebertt** [comment]
Sure. 
/close

**Pull request closed without merging**
