### PR TITLE
Allow MCM to list and watch PDBs

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind bug

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by minchaow — COMMENTED** [review]
Thanks for your fix so much.
I am wondering about the permission in the following two files https://github.com/gardener/gardener-extension-provider-alicloud/blob/master/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml and  https://github.com/gardener/gardener-extension-provider-alicloud/blob/master/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, do they also need permission of PDBs?

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
> Thanks for your fix so much.
> I am wondering about the permission in the following two files https://github.com/gardener/gardener-extension-provider-alicloud/blob/master/charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml and https://github.com/gardener/gardener-extension-provider-alicloud/blob/master/charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml, do they also need permission of PDBs?

Nope

**Pull request merged**
