### PR TITLE
vendor gardener and use worker secret ref. for the machine class credentialsSecretRef

### PR DESCRIPTION
**Pull request by danielfoehrKn**
**How to categorize this PR?**

/area quality
/kind enhancement
/priority normal
/platform alicloud

**What this PR does / why we need it**:
Uses the machine classes  .{spec.}credentialsSecretRef field. It is a reference to a secret containing only the credentials, while today's .{spec.}secretRef still contains the user-data. See [here for more details](https://github.com/gardener/machine-controller-manager/pull/578).

Uses the worker's secret reference as the credentialsSecretRef.
This means all worker pools use the same "cloudprovider" secret containing only the cloud provider credentials.
The existing MachineClass SecretReference then only contains the user data that is different for each pool. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Reducing credential update complexity by all the machine classes using the new .{spec.}credentialsSecretRef field.
This means all worker pools use the same "cloudprovider" secret containing only the cloud provider credentials.
The existing MachineClass SecretReference only contains the user data that is different for each pool.
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/invite @minchaow 
Do you want to merge this PR and include it in your current release validation?

**Comment by minchaow** [comment]
> /lgtm
> /invite @minchaow
> Do you want to merge this PR and include it in your current release validation?

I think it is fine to include this PR in current release validation. I could trigger a another validation deployment when the PR is merged.

**Review by minchaow — APPROVED** [review]
/lgtm

**Review by prashanth26 — APPROVED** [review]
/lgtm

Had similar changes with AWS and seemed to work as expected.

**Pull request merged**
