### PR TITLE
adapt nodeTemplate in MachineClass

### PR DESCRIPTION
**Pull request by AxiomSamarth**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
This PR adopts `nodeTemplate` field from the worker resource while creating the `MachineClasses` as needed by Cluster Autoscaler for a generic scale from zero.

**Which issue(s) this PR fixes**:
Fixes [Autoscaler/#27](https://github.com/gardener/autoscaler/issues/27)

**Special notes for your reviewer**:
- Gardener v1.38 & latest MCM must be vendored. Until then the build may fail.

**Release note**:

```feature user
NONE
```

### CODE REVIEW

**Comment by rfranzke** [comment]
/rebase
cc @himanshu-kun Can you take over?

**Comment by himanshu-kun** [comment]
/hold
will revendor MCM v0.43 and mark unhold

**Comment by shaoyongfeng** [comment]
Hi @himanshu-kun ，
MCM v0.43 was vendored via https://github.com/gardener/gardener-extension-provider-alicloud/pull/417.
can you continue this PR?

**Comment by rfranzke** [comment]
What about this PR? Can it be merged now?

**Review by EmoinLanyu — APPROVED** [review]
/lgtm

**Comment by EmoinLanyu** [comment]
@shaoyongfeng Can we merge this PR now?

**Comment by himanshu-kun** [comment]
/unhold
yes it can be merged now. Thanks for your patience.

**Pull request merged**
