### PR TITLE
[release-v1.24] Regenerated controllerregistration

### PR DESCRIPTION
**Pull request by himanshu-kun**
**How to categorize this PR?**

/area delivery
/kind cleanup
/platform alicloud

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @himanshu-kun for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by vpnachev — APPROVED** [review]
Thanks!
/reviewed ok-to-test
/lgtm

It looks like @minchaow forgot to run `make generate` for https://github.com/gardener/gardener-extension-provider-alicloud/commit/028fcceaa40e4c456823f36159bfc7465351f959.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
